function och(){
    document.querySelector(".areomet").style = "display:block;"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"

}
function och1(){
    document.querySelector(".glava").style = "display:block;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"


}
function och2(){
    document.querySelector(".vtulka").style = "display:block"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"


}
function och3(){
    document.querySelector(".vtulka1").style = "display:block"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"


}
function och4(){
    document.querySelector(".zvezda").style = "display:block"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"

}
function och5() {
    document.querySelector(".igol").style = "display:block"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"


}
function och6() {
    document.querySelector(".korpus").style = "display:block"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"


}
function och7() {
    document.querySelector(".vtulka3").style = "display:block"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"


}
function och8() {
    document.querySelector(".sharik").style = "display:block"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"

}
function och9() {
    document.querySelector(".krep").style = "display:block"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"


}
function och10() {
    document.querySelector(".mano").style = "display:block"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"

}
function och11() {
    document.querySelector(".muft").style = "display:block"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"


}
function och12() {
    document.querySelector(".obgon").style = "display:block"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"


}
function och13() {
    document.querySelector(".opor").style = "display:block"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"

    
}
function och14() {
    document.querySelector(".podshiv").style = "display:block"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"

    
}
function och15() {
    document.querySelector(".podshiv1").style = "display:block"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"

}
function och16() {
    document.querySelector(".podshiv2").style = "display:block"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"

}
function och17() {
    document.querySelector(".razem").style = "display:block"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"

}
function och18() {
    document.querySelector(".remen").style = "display:block"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".sistema").style = "display:none"

}
function och19() {
    document.querySelector(".rolik").style = "display:block"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"
    document.querySelector(".sistema").style = "display:none"
    
}

function och20() {
    document.querySelector(".sistema").style = "display:block"
    document.querySelector(".rolik").style = "display:none"
    document.querySelector(".remen").style = "display:none"
    document.querySelector(".razem").style = "display:none"
    document.querySelector(".podshiv2").style = "display:none"
    document.querySelector(".podshiv1").style = "display:none"
    document.querySelector(".podshiv").style = "display:none"
    document.querySelector(".opor").style = "display:none"
    document.querySelector(".obgon").style = "display:none"
    document.querySelector(".muft").style = "display:none"
    document.querySelector(".mano").style = "display:none"
    document.querySelector(".krep").style = "display:none"
    document.querySelector(".sharik").style = "display:none"
    document.querySelector(".vtulka3").style = "display:none"
    document.querySelector(".korpus").style = "display:none"
    document.querySelector(".igol").style = "display:none"
    document.querySelector(".zvezda").style = "display:none"
    document.querySelector(".vtulka1").style = "display:none"
    document.querySelector(".vtulka").style = "display:none"
    document.querySelector(".glava").style = "display:none;"
    document.querySelector(".areomet").style = "display:none;"

    
}