var data = [
  {
    name: "مشعل گازسوز ایران رادیاتور مدل F 55 ا F 55",
    price: "از ۵٫۸۰۰٫۰۰۰ تومان",
    creator: "در ۳۰ فروشگاه",
    crator: 1,
    madel: 1,
    image:
      "https://image.torob.com/base/images/23/D8/23D8hPWFY81PkCsL.jpg_/280x280.webp",
    image2:
      "https://image.torob.com/base/images/e4/d2/e4d2-DGDyEX415-Z.jpg_/280x280.webp",
    image3:
      "https://image.torob.com/base/images/Ck/kH/CkkHT3lZUd-sSifK.jpg_/280x280.webp",
    Funktsiya: "گرمایش و آبگرم",
    turi: "گازی",
    Ornatish: "زمینی",
    olchami: "270*320*350 میلیمتر",
    ogirligi: "6 کیلوگرم",
    ochilishining_diametri: "80 میلی متر",
    foydalanish: "تا 200 متر مربع (2 طبقه)",
    Energiya: "B",
    foydalanuvchi:"تامین ابگرم مصرفی، کاربری های نیمه صنعتی مانند نانوایی، خشکشویی، اتوشویی",
    Isitish_quvvati: "64 کیلووات",
    issiqlik_quvvati: "17,000 الی 43,000 کیلوکالری",
    Istemol_qilinadigan_elektr_energiyasi_turi: "تک فاز",
    Dvigatel: "0.050 کیلووات",
    gaz_istemoli: "5.2 مترمکعب در ساعت ( حداکثر ظرفیت)",
    Ulanish_olchami: "1/2",
    Ishlab_chiqaruvchi: "ایران",
    sotishdan_keyingi: "گروه صنعتی ایران رادیاتور",
    yoqilgi: "",
    Bepul_narsalar:
      "شیر برقی گاز 1/2 | فلو سوئیچ هوا | پرشر سوئیچ گاز | رله کنترل G790 شکوه",
  },
  {
    name: "مشعل گازی تک شعله اتال ، مشعل شیپوری اتال مدل تک شعله ا Linear Trumpet Gas Burner made by OTAL",
    price: "۱٫۴۵۰٫۰۰۰ تومان",
    creator:
      "مشعل گازی تک شعله اتال ، مشعل شیپوری اتال مدل تک شعله ا Linear Trumpet Gas Burner made by OTAL",
    crator: "",
    madel: "",
    image:
      "https://image.torob.com/base/images/sb/-E/sb-ElGTsiE4Fv1pH.jpg_/280x280.webp",
    image2: "",
    image3: "",
    Funktsiya: "",
    turi: "",
    Ornatish: "",
    olchami: "",
    ogirligi: "",
    ochilishining_diametri: "",
    foydalanish: "",
    Energiya: "",
    foydalanuvchi: "",
    Isitish_quvvati: "",
    issiqlik_quvvati: "",
    Istemol_qilinadigan_elektr_energiyasi_turi: "",
    Dvigatel: "",
    gaz_ist۲۴۹٫۱۵۸٫۰۰۰ تومانova: "مناسب انواع تنور سنتی سنگکی ، بربری ، نان روغنی و ...",
    Yonginga_chidamli_diametri: "90 میلی متر",
    shamdon: "دارای شمعک",
    Chiroq_uzunligi: "60 سانتی متر و قابلیت ساخت مطابق سفارش مشتری",
    gaz_klapan: "1/2 اینچ",
    Diametrli_quvur: "2 اینچ (55 میلی متر)",
    havo_damperi: "دستی",

    Bepul_narsalar: "",
  },
  {
    name: "مشعل گازی گرم ایران مدل GNG 90/60 ا مشعل گازسوز نیروگاهی گرم ایران مدل 60/GNG 90",
    price: "۵ فروشنده دیگر",
    creator: "",
    crator: "",
    madel: "",
    image: "https://image.torob.com/base/images/gL/Od/gLOdRLLTb7RnIrOB.jpg_/280x280.webp",
    image2: "",
    image3: "",
    Funktsiya: "",
    turi: "",
    Ornatish: "",
    olchami: "",
    ogirligi: "",
    ochilishining_diametri: "",
    foydalanish: "",
    Energiya: "",
    foydalanuvchi: "",
    Isitish_quvvati: "",
    issiqlik_quvvati: "",
    Istemol_qilinadigan_elektr_energiyasi_turi: "",
    Dvigatel: "",
    gaz_istemoli: "",
    Ulanish_olchami: "",
    Ishlab_chiqaruvchi: "",
    sotishdan_keyingi: "",

    yoqilgi: "گاز شهری",
    Nominal_issiqlik: "بیش از 1000000",
    Kirish_issiqlik: "1500000-6200000",
    Elektr_energiyasi_istemoli: "سه فاز 400 ولت",
    MM_olchamlari: "2835/1150/1680/415",
    Ishlab_chiqaruvchi_mamlakat: "ایران",
    Bepul_ornatish: "ندارد",
    Ishlash: "سه مرحله ای",
    Dvigatel_quvvati_K: "18.5",
    Boshqarish_rölesi: "TMG740",
    Brülör_ochilishining_diametri_mm: "415",
    Chiroq_aksessuarlari:
      "خط گاز کامل به همراه تابلو برق اتصال ترمینالهای مدار فرمان",
    Servo_motor: "دارد",
    brend: "گرم ایران",
    Bepul_narsalar: "",
  },
  {
    name: "مشعل گازی خطی اتال ، مشعل شیپوری اتال مدل خطی ا Linear Trumpet Gas Burner made by OTAL",
    price: "۱٫۲۰۰٫۰۰۰ تومان",
    creator: "",
    crator: "",
    madel: "",
    image: "https://image.torob.com/base/images/tU/Og/tUOgwRwrQbyEsdMD.jpg_/280x280.webp",
    image2: "",
    image3: "",
    Funktsiya: "",
    turi: "",
    Ornatish: "",
    olchami: "",
    ogirligi: "",
    ochilishining_diametri: "",
    foydalanish: "",
    Energiya: "",
    foydalanuvchi: "",
    Isitish_quvvati: "",
    issiqlik_quvvati: "",
    Istemol_qilinadigan_elektr_energiyasi_turi: "",
    Dvigatel: "",
    gaz_istemoli: "",
    Ulanish_olchami: "",
    Ishlab_chiqaruvchi: "",
      sotishdan_keyingi: "",
    
      yoqilgi: "گاز شهری و گاز مایع کپسول (LPG)",
      Ilova: "مناسب برای تنور نانوایی سنتی و صنعتی پخت نان لواش ، تافتون ، سنگک ، بربری و ...",
    Chiroq_uzunligi:"94 سانتی متر و قابلیت ساخت مطابق سفارش مشتری",
      olov_uzunligi: "55 سانتی متر و قابلیت ساخت مطابق سفارش مشتری",
      gaz_klapan: "1/2 اینچ",
      Diametrli_quvur: "2 اینچ (55 میلی متر)",
      havo_damperi: "دستی",
      shamdon: "دارای شمعک",

    Bepul_narsalar: "",
  },
  {
    name: "مشعل گازی ایران رادیاتور مدل JGN80/2 ا mashal",
    price: "از ۱۱٫۵۵۰٫۰۰۰ تومان",
    creator: "",
    crator: "",
    madel: "ایران رادیاتور JGN 80/2",
    image: "https://image.torob.com/base/images/Xa/1J/Xa1J1vRutdi4xsRT.jpg_/280x280.webp",
    image2: "https://image.torob.com/base/images/e4/d2/e4d2-DGDyEX415-Z.jpg_/280x280.webp",
    image3: "https://image.torob.com/base/images/xX/6M/xX6M0tFezAAlP647.jpg_/280x280.webp",
    turi:"گازی",
    Funktsiya: "گرمایش و آبگرم",
    Ornatish: "زمینی",
    olchami: "550*380*460 میلیمتر",
    ogirligi: "14 کیلوگرم",
    ochilishining_diametri: "110 میلی متر",
    foydalanish: "تا 1200 متر مربع (5 طبقه)",
    Energiya: "B",
    foydalanuvchi: "تامین ابگرم مصرفی، کاربری های نیمه صنعتی مانند خشکشویی، اتوشویی",
    Isitish_quvvati: "240 کیلووات",
    issiqlik_quvvati: "52,000 الی 225,000 کیلوکالری",
    Istemol_qilinadigan_elektr_energiyasi_turi: "تک فاز",
    Dvigatel: "0.24 کیلووات",
    gaz_istemoli: "27.5 مترمکعب در ساعت ( حداکثر ظرفیت)",
    Ulanish_olchami: "1",
    Ishlab_chiqaruvchi: "ایران",
    sotishdan_keyingi: "گروه صنعتی ایران رادیاتور",
    Bepul_narsalar: "شیر برقی گاز تدریجی 1 اینچ | پرشر سوئیچ هوا | پرشر سوئیچ گاز | رله کنترل G790 شکوه",
  },
  {
    name: "مشعل گازی شیپوری تنوری سه چهارم اصفهان گاز",
    price: "۱٫۳۵۰٫۰۰۰ تومان",
    creator: "",
    crator: "",
      madel: "",
    Mahsulot_identifikatori:"403",
    image: "https://image.torob.com/base/images/hZ/7t/hZ7t2CfFHqDcDlbb.jpg_/280x280.webp",
    image2: "",
    image3: "",
    Funktsiya: "",
    turi: "",
    Ornatish: "",
    olchami: "",
    ogirligi: "",
    ochilishining_diametri: "",
    foydalanish: "",
    Energiya: "",
    foydalanuvchi: "",
    Isitish_quvvati: "",
    issiqlik_quvvati: "",
    Istemol_qilinadigan_elektr_energiyasi_turi: "",
    Dvigatel: "",
    gaz_istemoli: "",
    Ulanish_olchami: "",
    Ishlab_chiqaruvchi: "",
    sotishdan_keyingi: "",
    yoqilgi: "",
    Bepul_narsalar: "",
  },
  {
    name: "مشعل اتمسفریک گازسوز و بدون صدای اخگر",
    price: "۱ فروشنده دیگر",
    creator: "",
    crator: "",
    madel: "VE1, VE2, VE3",
    image: "https://image.torob.com/base/images/L5/K_/L5K_UENKh7xNQiW0.jpg_/280x280.webp",
    image2: "",
    image3: "",
    Funktsiya: "",
    turi: "",
    Ornatish: "",
    olchami: "",
    ogirligi: "",
    ochilishining_diametri: "",
    foydalanish: "",
    Energiya: "",
    foydalanuvchi: "",
    Isitish_quvvati: "",
    issiqlik_quvvati: "",
    Istemol_qilinadigan_elektr_energiyasi_turi: "",
    Dvigatel: "",
    gaz_istemoli: "",
    Ulanish_olchami: "",
    Ishlab_chiqaruvchi: "",
    sotishdan_keyingi: "",
    yoqilgi: "",
    Bepul_narsalar: "",
  },
  {
    name: "مشعل گاز سوز 102000-37000 ایران رادیاتور مدل RAN 25 ا Iran Radiator RAN 25 Gas Burner 37000-102000",
    price: "از ۸٫۶۵۰٫۰۰۰ تومان",
    creator: "",
    crator: "",
    madel: "ایران رادیاتور RAN 25",
    image: "https://image.torob.com/base/images/Zb/2R/Zb2Rm4IUWzf26EWt.jpg_/280x280.webp",
    image2: "",
      image3: "",
      turi: "گازی",
    Funktsiya: "گرمایش و آبگرم",
    Ornatish: "زمینی",
    olchami: "460*320*420 میلیمتر",
    ogirligi: "10 کیلوگرم",
    ochilishining_diametri: "88 میلی متر",
    foydalanish: "تا 600 متر مربع (4 طبقه)",
    Energiya: "B",
    foydalanuvchi: "تامین ابگرم مصرفی، کاربری های نیمه صنعتی مانند نانوایی، خشکشویی، اتوشویی",
    Isitish_quvvati: "124 کیلووات",
    issiqlik_quvvati: "37,000 الی 102,000 کیلوکالری",
    Istemol_qilinadigan_elektr_energiyasi_turi: "تک فاز",
    Dvigatel: "0.09 کیلووات",
    gaz_istemoli: "12.5 مترمکعب در ساعت ( حداکثر ظرفیت)",
    Ulanish_olchami: "1/2",
    Ishlab_chiqaruvchi: "ایران",
    sotishdan_keyingi: "گروه صنعتی ایران رادیاتور",
    Bepul_narsalar: "شیر برقی تدریجی گاز 1/2 اینچ | پرشر سوئیچ هوا | پرشر سوئیچ گاز | رله کنترل G790 شکوه",
  },
  {
    name: "چندراهه مشعل ونزیا 24",
    price: "۴۲۵٫۶۴۵ تومان",
    creator: "",
    crator: "",
    madel: "",
    image: "https://image.torob.com/base/images/UN/iL/UNiLGfoiJz10bgwQ.webp_/280x280.webp",
    image2: "",
    image3: "",
    Funktsiya: "",
    turi: "",
    Ornatish: "",
    olchami: "",
    ogirligi: "",
    ochilishining_diametri: "",
    foydalanish: "",
    Energiya: "",
    foydalanuvchi: "",
    Isitish_quvvati: "",
    issiqlik_quvvati: "",
    Istemol_qilinadigan_elektr_energiyasi_turi: "",
    Dvigatel: "",
    gaz_istemoli: "",
    Ulanish_olchami: "",
    Ishlab_chiqaruvchi: "",
    sotishdan_keyingi: "",
    yoqilgi: "",
      Bepul_narsalar: "",
    brend:"گروه صنعتی بوتان",
  },

  {
    name: "مشعل گازی ایران رادیاتور مدل GMG 110 ا GMG 110",
    price: "۱۶ فروشنده دیگر",
    creator: "",
    crator: "",
    madel: "ایران رادیاتور GMG110",
    image: "https://image.torob.com/base/images/J8/0K/J80KWyyw0d97bteO.jpg_/280x280.webp",
    image2: "https://image.torob.com/base/images/J8/0K/J80KWyyw0d97bteO.jpg_/280x280.webp",
      image3: "",
      turi: "گازی",
    Funktsiya: "گرمایش و آبگرم",
    Ornatish: "زمینی",
    olchami: "420*540*500 میلیمتر",
    ochilishining_diametri: "120 میلی متر",
    foydalanish: "تا 500 متر مربع زیربنا",
    Energiya: "A+",
    foydalanuvchi: "تامین ابگرم مصرفی (دیگ آبگرم چدنی و فولادی)کاربری های نیمه صنعتی مانند نانوایی، خشکشویی، اتوشوییهیترهای صنعتی و کوره هوای گرم",
    Isitish_quvvati: "140 کیلووات",
    issiqlik_quvvati: "109.000 کیلوکالری",
    Istemol_qilinadigan_elektr_energiyasi_turi: "تک فاز",
    Dvigatel: "0.24 کیلووات",
    gaz_istemoli: "4.2 - 11.5 مترمکعب در ساعت",
    Ulanish_olchami: "3/4 اینچ یا 1 اینچ (ورودی گاز)",
    Ishlab_chiqaruvchi: "ایران",
    sotishdan_keyingi: "گروه صنعتی ایران رادیاتور",
    Bepul_narsalar: "شیر برقی تدریجی گاز 1 اینچفلو سوئیچ هواپرشر سوئیچ گازرله کنترل G790 شکوه",
  },

  {
    name: "مشعل گازوئیل سوز ایران رادیاتور مدل JPE 80/1 ا JPE 80/1",
    price: "از ۷٫۶۰۰٫۰۰۰ تومان",
    creator: "",
    crator: "",
    madel: "ایران رادیاتور JPE 80/1",
    image: "https://image.torob.com/base/images/lx/Wq/lxWqIrO7yBASfryE.jpg_/280x280.webp",
    image2: "https://image.torob.com/base/images/XJ/Em/XJEmy2peRoOshj4o.jpg_/280x280.webp",
    image3: "",
      turi: "گازوئیلی",
      Funktsiya: "گرمایش و آبگرم",
    Ornatish: "زمینی",
    olchami: "390*360*600 میلیمتر",
    ogirligi: "10 کیلوگرم (حدودی)",
    ochilishining_diametri: "110 میلی متر",
    foydalanish: "تا 900 متر مربع (5 طبقه)",
    Energiya: "B",
    foydalanuvchi: "تامین ابگرم مصرفی، کاربری های نیمه صنعتی مانند نانوایی، خشکشویی، اتوشویی",
    Isitish_quvvati: "186 کیلووات",
    issiqlik_quvvati: "70,000 الی 160,000 کیلوکالری",
    Istemol_qilinadigan_elektr_energiyasi_turi: "تک فاز",
    Dvigatel: "0.24 کیلووات",
    Dizel_istemoli: "7 الی 16 کیلوگرم در ساعت",
    Ulanish_olchami: "1/8 اینچ",
    Ishlab_chiqaruvchi: "ایران",
    sotishdan_keyingi: "گروه صنعتی ایران رادیاتور",
    Bepul_narsalar: "شیر برقی 1/8 اینچ - پمپ سانتک 47C یا مشابه - رله کنترل TF701 شکوه - چشم الکترونیک",
  },

  {
    name: "مشعل گازسوز ایران رادیاتور مدل PGN 1 ا PGN 1",
    price: "۴ فروشنده دیگر",
    creator: "",
    crator: "",
    madel: "PGN 1",
    image: "https://image.torob.com/base/images/p9/CU/p9CUnQYpFr2VD0QC.jpg_/280x280.webp",
    image2: "",
    image3: "",
    Funktsiya: "",
    turi: "",
    Ornatish: "",
    olchami: "",
    ogirligi: "",
    ochilishining_diametri: "",
    foydalanish: "",
    Energiya: "",
    foydalanuvchi: "",
    Isitish_quvvati: "",
    issiqlik_quvvati: "",
    Istemol_qilinadigan_elektr_energiyasi_turi: "",
    Dvigatel: "",
    gaz_istemoli: "",
    Ulanish_olchami: "",
    Ishlab_chiqaruvchi: "",
    sotishdan_keyingi: "",
    yoqilgi: "",
      Bepul_narsalar: "",
    
      Minimal_issiqlik_quvvati_Kkal_soat: "212,000",
      Maksimal_issiqlik_quvvati_Kkal_soat: "800,000",
      Ishlash: "دو مرحله ای",
      boshqaruv_paneli:"مجزا",
      havo_damperi: "اتوماتیک",
      Elektr_dvigatelining_texnik_xususiyatlari: "3Ф ~ 1.5 KW",
      Servo_motor_modeli: "LKS 160",
      Rele_turi: "TMG 740",
      Minimal_gaz_bosimi_m_Bar: "20",
      Gaz_quvurining_olchami: "2",
      Chiroqning_umumiy_uzunligi_mm: "810",
      Olov_qoplamining_uzunligi_mm: "200",
      Olovli_pechning_umumiy_kengligi_mm: "675",
      Olov_qopqogining_diametri_mm: "165",
      Chiroqli_aksessuarlar: "1 عدد شیر برقی گاز تکضرب 1/2 1 ، 1 عدد شیر برقی گاز تدریجی دو مرحله ای 1/2 1 ، پرشر هوا و گاز",
      Tegishli_gaz_quvuri_modeli: "GTE 800",
      Ishlab_chiqaruvchi_mamlakat:"ایران",
  },

  {
    name: "مشعل گلخانه ای ، مشعل شیپوری اُتال مدل شعله مستقیم مناسب هیتر گلخانه ای",
    price: "۱٫۱۰۰٫۰۰۰ تومان",
    creator: "",
    crator: "",
    madel: "مشعل گازی شیپوری اُتال ، مشعل شیپوری مدل شعله مستقیم",
    image: "https://image.torob.com/base/images/KA/YE/KAYECMKZkw-dLQpu.jpg_/280x280.webp",
    image2: "",
    image3: "",
    Funktsiya: "",
    turi: "",
    Ornatish: "",
    olchami: "",
    ogirligi: "",
    ochilishining_diametri: "",
    foydalanish: "",
    Energiya: "",
    foydalanuvchi: "",
    Isitish_quvvati: "",
    issiqlik_quvvati: "",
    Istemol_qilinadigan_elektr_energiyasi_turi: "",
    Dvigatel: "",
    gaz_istemoli: "",
    Ulanish_olchami: "",
    Ishlab_chiqaruvchi: "",
    sotishdan_keyingi: "",
      Bepul_narsalar: "",
    
      yoqilgi_turi: "گاز شهری و گاز مایع LPG (کپسول ",
      Chiroqning_umumiy_uzunligi: "55 سانتیمتر و قابلیت ساخت طبق سفارش مشتری",
      Qobiliyat: "تبدیل شدن به سیستم کاملا اتومات",
      Diametrli_quvur:"2 اینچ (55 میلیمتر)",
      Ilova: "مناسب بخاری ، هیتر گلخانه ای و کوره هوای گرم دست ساز فلزی برای گرمایش گلخانه ها و سالن ها و ...",
      gaz_klapan: "1/2 اینچ",
      shamdon: "دارای شمعک",
havo_damperi:"دستی",
  },

  {
    name: "مشعل اجاق گاز",
    price: "۹۰۰٫۰۰۰ تومان",
    creator: "",
    crator: "",
    madel: "",
    image: "https://image.torob.com/base/images/7q/fS/7qfSrkj1BnE3k43B.jpg_/280x280.webp",
    image2: "",
    image3: "",
    Funktsiya: "",
    turi: "",
    Ornatish: "",
    olchami: "",
    ogirligi: "",
    ochilishining_diametri: "",
    foydalanish: "",
    Energiya: "",
    foydalanuvchi: "",
    Isitish_quvvati: "",
    issiqlik_quvvati: "",
    Istemol_qilinadigan_elektr_energiyasi_turi: "",
    Dvigatel: "",
    gaz_istemoli: "",
    Ulanish_olchami: "",
    Ishlab_chiqaruvchi: "",
    sotishdan_keyingi: "",
    yoqilgi: "",
      Bepul_narsalar: "",
    
      Mahsulot_hajmi: "10cm, 12cm, 14cm, 16cm, 20cm, 25cm, 30cm, 40cm, 50cm, 70cm",
      mahsulot_turi: "معمولی, کوچک, بزرگ, توپر, قوی",
      ip_olchami: "2/5, 3",
      mahsulot_turi: "چدن",
      Mahsulot_identifikatori:"مشعل اجاق",
  },

  {
    name: "مشعل گازسوز گرم ایران مدل GNG 90/4 ا GNG 90/4",
    price: "از ۱۳٫۹۵۰٫۰۰۰ تومان",
    creator: "",
    crator: "",
    madel: "",
    image: "https://image.torob.com/base/images/ER/DB/ERDBJxCFmDr1gyy7.jpg_/280x280.webp",
    image2: "",
    image3: "",
      turi: "",
      Funktsiya: "",  
    Ornatish: "",
    olchami: "",
    ogirligi: "",
    ochilishining_diametri: "",
    foydalanish: "",
    Energiya: "",
    foydalanuvchi: "",
    Isitish_quvvati: "",
    issiqlik_quvvati: "",
    Istemol_qilinadigan_elektr_energiyasi_turi: "",
    Dvigatel: "",
    gaz_istemoli: "",
    Ulanish_olchami: "",
    Ishlab_chiqaruvchi: "",
    sotishdan_keyingi: "",
    yoqilgi: "",
    Bepul_narsalar: "",
  },

  {
    name: "",
    price: "",
    creator: "",
    crator: "",
    madel: "",
    image: "",
    image2: "",
    image3: "",
    Funktsiya: "",
    turi: "",
    Ornatish: "",
    olchami: "",
    ogirligi: "",
    ochilishining_diametri: "",
    foydalanish: "",
    Energiya: "",
    foydalanuvchi: "",
    Isitish_quvvati: "",
    issiqlik_quvvati: "",
    Istemol_qilinadigan_elektr_energiyasi_turi: "",
    Dvigatel: "",
    gaz_istemoli: "",
    Ulanish_olchami: "",
    Ishlab_chiqaruvchi: "",
    sotishdan_keyingi: "",
    yoqilgi: "",
    Bepul_narsalar: "",
  },

  {
    name: "",
    price: "",
    creator: "",
    crator: "",
    madel: "",
    image: "",
    image2: "",
    image3: "",
    Funktsiya: "",
    turi: "",
    Ornatish: "",
    olchami: "",
    ogirligi: "",
    ochilishining_diametri: "",
    foydalanish: "",
    Energiya: "",
    foydalanuvchi: "",
    Isitish_quvvati: "",
    issiqlik_quvvati: "",
    Istemol_qilinadigan_elektr_energiyasi_turi: "",
    Dvigatel: "",
    gaz_istemoli: "",
    Ulanish_olchami: "",
    Ishlab_chiqaruvchi: "",
    sotishdan_keyingi: "",
    yoqilgi: "",
    Bepul_narsalar: "",
  },
];